#' Reads in data file
#'
#' This is a function that reads in a FARS data file (with file name \code{filename}).
#' An error message is generated if the argument \code{filename} does not exist.
#'
#' @param filename A character string representing the name of the file to read in
#'
#' @return This function returns a data frame from the file input.
#'
#' @examples
#' fars_read("accident_2013.csv.bz2")
#'
#' @import dplyr
#' @importFrom readr read_csv
#'
#' @export
fars_read <- function(filename) {
  if(!file.exists(filename))
    stop("file '", filename, "' does not exist")
  data <- suppressMessages({
    readr::read_csv(filename, progress = FALSE)
  })
  dplyr::tbl_df(data)
}

#' Generates file name
#'
#' This is a function that generates for a given \code{year} the appropriate file name for the corresponding FARS data file.
#'
#' @param year A numeric value denoting the year during which data should be gathered
#'
#' @return This function returns a character string (the file name) corresponding to the given \code{year}.
#'
#' @examples
#' make_filename(2013)
#'
#' @export
make_filename <- function(year) {
  year <- as.integer(year)
  sprintf("accident_%d.csv.bz2", year)
}

#'  Generate data frame and select months and year
#'
#' This is a function that generates a data frame for given \code{years} (from the FARS data file)
#' using the functions \code{\link{make_filename}} and \code{link{fars_read}} and selects only the columns for month and year.
#' An error message ("invalid year") is printed if an associated data set cannot be found.
#'
#' @param years A numeric value denoting the year/ a list of years during which data should be gathered
#'
#' @return This function returns a data frame containing month and year for each data entry of the corresponding data set.
#'
#' @examples
#' fars_read_years(2013)
#'
#' @import dplyr
#'
#' @export
fars_read_years <- function(years) {
  lapply(years, function(year) {
    file <- make_filename(year)
    tryCatch({
      dat <- fars_read(file)
      dplyr::mutate(dat, year = year) %>%
        dplyr::select(MONTH, year)
    }, error = function(e) {
      warning("invalid year: ", year)
      return(NULL)
    })
  })
}

#' Yields sum of accidents for each month in a given year
#'
#' This is a function that summarizes the data frame generated by the function \code{\link{fars_read_years}}
#' yielding the sum of accidents for each month for given \code{years}.
#'
#' @inheritParams fars_read_years
#'
#' @return This function returns a data frame containing the number of accidents for each month in a given year.
#'
#' @examples
#' fars_summarize_years(2013)
#'
#' @import dplyr
#' @importFrom tidyr spread
#'
#' @export
fars_summarize_years <- function(years) {
  dat_list <- fars_read_years(years)
  dplyr::bind_rows(dat_list) %>%
    dplyr::group_by(year, MONTH) %>%
    dplyr::summarize(n = n()) %>%
    tidyr::spread(year, n)
}

#' Show accident density in a given state
#'
#' This is a function that generates a data frame for a given year (\code{years}) using the functions \code{\link{make_filename}} and \code{\link{fars_read}}
#' and plots the accidents for a given state (\cod{state.num}).
#' An error message is printed if \cod{state.num} does not appear in the FARS data set ("invalid STATE number")
#' or if no accidents appeared ("no accidents to plot")
#'
#' @param state.num A numerical value corresponding to a state in the FARS data frame
#' @param year A numeric value denoting the year during which data should be gathered
#'
#' @return This function plots the location of the accidents on a map of a given state in a given year
#'
#' @examples
#' fars_map_state(1,2013)
#'
#' @import maps
#' @import dplyr
#' @importFrom graphics points
#'
#' @export
fars_map_state <- function(state.num, year) {
  filename <- make_filename(year)
  data <- fars_read(filename)
  state.num <- as.integer(state.num)

  if(!(state.num %in% unique(data$STATE)))
    stop("invalid STATE number: ", state.num)
  data.sub <- dplyr::filter(data, STATE == state.num)
  if(nrow(data.sub) == 0L) {
    message("no accidents to plot")
    return(invisible(NULL))
  }
  is.na(data.sub$LONGITUD) <- data.sub$LONGITUD > 900
  is.na(data.sub$LATITUDE) <- data.sub$LATITUDE > 90
  with(data.sub, {
    maps::map("state", ylim = range(LATITUDE, na.rm = TRUE),
              xlim = range(LONGITUD, na.rm = TRUE))
    graphics::points(LONGITUD, LATITUDE, pch = 46)
  })
}
